language: java

jdk:
  - oraclejdk8

env:
  - PLAY_VERSION=2.5.3

before-script:
  - npm install

#script:
#  - play-${PLAY_VERSION}/play test
#  - play-${PLAY_VERSION}/play test:checkstyle
#  - npm run test
