language: scala
scala:
  - 2.11.7

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

env:
  - PLAY_VERSION=2.5.3

install:
  - npm install
#  - wget http://downloads.typesafe.com/releases/play-${PLAY_VERSION}.zip
#  - unzip -q play-${PLAY_VERSION}.zip

script:
  - ls -la
  - java -version
#  - play-${PLAY_VERSION}/play test
#  - play-${PLAY_VERSION}/play test:checkstyle
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION test:codestyle
  - npm run test
